#!/usr/bin/env python3
"""
Multi-Format Exporter for Course Materials
Day 3: Export to PDF, HTML, and Markdown
"""

import os
import markdown
from pathlib import Path
from typing import List, Dict, Any, Optional
from xhtml2pdf import pisa

class MultiExporter:
    def __init__(self, output_dir: str = "output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def export_content(self, content: str, base_filename: str, formats: List[str]) -> List[str]:
        """Export content to multiple formats"""
        if 'all' in formats:
            formats = ['pdf', 'html', 'markdown']
        
        generated_files = []
        
        for format in formats:
            try:
                if format == 'pdf':
                    filename = self._export_to_pdf(content, base_filename)
                elif format == 'html':
                    filename = self._export_to_html(content, base_filename)
                elif format == 'markdown':
                    filename = self._export_to_markdown(content, base_filename)
                else:
                    continue
                
                if filename:
                    generated_files.append(filename)
                    
            except Exception as e:
                print(f"❌ Error exporting {base_filename} to {format}: {e}")
        
        return generated_files
    
    def _export_to_pdf(self, content: str, base_filename: str) -> Optional[str]:
        """Export content to PDF"""
        try:
            # Convert markdown to HTML first
            html_content = markdown.markdown(content)
            
            # Create styled HTML
            styled_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {{
                        font-family: Arial, sans-serif;
                        margin: 40px;
                        line-height: 1.6;
                        color: #333;
                    }}
                    h1 {{
                        color: #2c3e50;
                        border-bottom: 2px solid #3498db;
                        padding-bottom: 10px;
                    }}
                    h2 {{
                        color: #34495e;
                        margin-top: 30px;
                    }}
                    h3 {{
                        color: #7f8c8d;
                    }}
                    table {{
                        width: 100%;
                        border-collapse: collapse;
                        margin: 20px 0;
                    }}
                    th, td {{
                        border: 1px solid #ddd;
                        padding: 12px;
                        text-align: left;
                    }}
                    th {{
                        background-color: #3498db;
                        color: white;
                    }}
                    tr:nth-child(even) {{
                        background-color: #f2f2f2;
                    }}
                    code {{
                        background-color: #f8f9fa;
                        padding: 2px 4px;
                        border-radius: 3px;
                        font-family: 'Courier New', monospace;
                    }}
                    .footer {{
                        margin-top: 50px;
                        font-size: 0.8em;
                        color: #7f8c8d;
                        text-align: center;
                    }}
                </style>
            </head>
            <body>
                {html_content}
                <div class="footer">
                    Generated by Course Automation System
                </div>
            </body>
            </html>
            """
            
            output_file = self.output_dir / f"{base_filename}.pdf"
            
            with open(output_file, "wb") as f:
                pisa_status = pisa.CreatePDF(styled_html, dest=f)
            
            if getattr(pisa_status, "err", False):
                print(f"❌ PDF creation error for {base_filename}")
                return None
            
            return str(output_file)
            
        except Exception as e:
            print(f"❌ PDF export failed for {base_filename}: {e}")
            return None
    
    def _export_to_html(self, content: str, base_filename: str) -> Optional[str]:
        """Export content to HTML"""
        try:
            html_content = markdown.markdown(content)
            
            styled_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>{base_filename}</title>
                <style>
                    body {{
                        font-family: Arial, sans-serif;
                        max-width: 800px;
                        margin: 0 auto;
                        padding: 20px;
                        line-height: 1.6;
                        color: #333;
                    }}
                    h1 {{
                        color: #2c3e50;
                        border-bottom: 2px solid #3498db;
                        padding-bottom: 10px;
                    }}
                    h2 {{
                        color: #34495e;
                        margin-top: 30px;
                    }}
                    table {{
                        width: 100%;
                        border-collapse: collapse;
                        margin: 20px 0;
                    }}
                    th, td {{
                        border: 1px solid #ddd;
                        padding: 12px;
                        text-align: left;
                    }}
                    th {{
                        background-color: #3498db;
                        color: white;
                    }}
                    tr:nth-child(even) {{
                        background-color: #f2f2f2;
                    }}
                    .footer {{
                        margin-top: 50px;
                        font-size: 0.8em;
                        color: #7f8c8d;
                        text-align: center;
                    }}
                </style>
            </head>
            <body>
                {html_content}
                <div class="footer">
                    Generated by Course Automation System
                </div>
            </body>
            </html>
            """
            
            output_file = self.output_dir / f"{base_filename}.html"
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(styled_html)
            
            return str(output_file)
            
        except Exception as e:
            print(f"❌ HTML export failed for {base_filename}: {e}")
            return None
    
    def _export_to_markdown(self, content: str, base_filename: str) -> Optional[str]:
        """Export content to Markdown (already in markdown format)"""
        try:
            output_file = self.output_dir / f"{base_filename}.md"
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(content)
            
            return str(output_file)
            
        except Exception as e:
            print(f"❌ Markdown export failed for {base_filename}: {e}")
            return None