"""Initial test

Revision ID: a9f7a2bbc3f5
Revises: 
Create Date: 2026-04-24 06:50:06.274432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f7a2bbc3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_outcomes_course_id'))

    op.drop_table('learning_outcomes')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_course_order'))
        batch_op.drop_index(batch_op.f('ix_lessons_course_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('assessment_formats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_formats_course_id'))

    op.drop_table('assessment_formats')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_course_id'))

    op.drop_table('tools')
    op.drop_table('lesson_learning_outcome_assoc')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_level_language'))
        batch_op.drop_index(batch_op.f('ix_courses_course_code'))
        batch_op.drop_index(batch_op.f('ix_courses_instructor'))

    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('course_title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('instructor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), nullable=True),
    sa.Column('delivery_mode', sa.VARCHAR(length=50), nullable=True),
    sa.Column('aim', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('objectives', sa.TEXT(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('updated_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_instructor'), ['instructor'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_course_code'), ['course_code'], unique=1)
        batch_op.create_index(batch_op.f('ix_course_level_language'), ['level', 'language'], unique=False)

    op.create_table('lesson_learning_outcome_assoc',
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('learning_outcome_id', sa.INTEGER(), nullable=False),
    sa.Column('strength', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'learning_outcome_id'),
    sa.UniqueConstraint('lesson_id', 'learning_outcome_id', name=op.f('uq_lesson_lo'))
    )
    op.create_table('tools',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('purpose', sa.TEXT(), nullable=True),
    sa.Column('license_info', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_course_id'), ['course_id'], unique=False)

    op.create_table('assessment_formats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('format_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_formats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_formats_course_id'), ['course_id'], unique=False)

    op.create_table('lessons',
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('lesson_title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('assignment_description', sa.TEXT(), nullable=True),
    sa.Column('materials_needed', sa.TEXT(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_course_order'), ['course_id', 'order'], unique=False)

    op.create_table('learning_outcomes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('outcome_text', sa.TEXT(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_outcomes_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###
